language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -f -t jonyhay/docker-react Dockerfile.dev .

script:
  - docker run jonyhay/docker-react npm run test -- --coverage