language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t jonyhay/docker-react .

script:
  - docker run -e CI=true jonyhay/docker-react npm run test -- --coverage