version: '3.0'
services:
    web:
        environment: 
            - CHOKIDAR_USEPOLLING=true # Windows, so code auto-reloads.
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        environment: 
            - CHOKIDAR_USEPOLLING=true # Windows, so code auto-reloads.
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
